[package]
name = "ssh2proxy-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
russh = { workspace = true }
fast-socks5 = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
